CREATE DATABASE QUANLYHOAXUAN_SQL
USE QUANLYHOAXUAN_SQL
CREATE TABLE LOAI
(
	MA_LOAI VARCHAR(9) NOT NULL,
    TEN_LOAI NVARCHAR(50),
    PRIMARY KEY(MA_LOAI)
)
CREATE TABLE KHACHHANG (
MA_KH VARCHAR(9) NOT NULL,
TEN_KH NVARCHAR(50),
QUANHUYEN NVARCHAR(50),
TINHTP NVARCHAR(50),
PRIMARY KEY(MA_KH)
)
CREATE TABLE HANGHOA (
MA_HH VARCHAR(9) NOT NULL,
TEN_HH NVARCHAR(50),
DV_TINH INT(10),
GIA DECIMAL(10),
MA_LOAI VARCHAR(5) NOT NULL,
PRIMARY KEY(MA_HH),
FOREIGN KEY(MA_LOAI) REFERENCES LOAI(MA_LOAI)
)
CREATE TABLE HOADON (
MA_HD VARCHAR(5) NOT NULL,
TEN_HD NVARCHAR(50),
NGAYLAP DATETIME,
MA_KH VARCHAR(9) NOT NULL,
PRIMARY KEY(MA_HD),
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH)
)
CREATE TABLE CHITIET (
SO_LUONG INT(5),
THANHTIEN DECIMAL(12),
MA_KH VARCHAR(9) NOT NULL,
MA_HH VARCHAR(9) NOT NULL,
PRIMARY KEY(MA_KH,MA_HH),
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH),
FOREIGN KEY(MA_HH) REFERENCES HANGHOA(MA_HH)
)